### ISSUE TITLE
Textures go black.

### ISSUE THREAD

**Issue by danielshervheim** [Scrawk/Brunetons-Improved-Atmospheric-Scattering#2]
The textures seem to be unloading prematurely, or something.
When I enter play mode, everything looks great!
![screen shot 2018-07-17 at 23 29 15](https://user-images.githubusercontent.com/41355080/42859549-44b4f63c-8a19-11e8-9d7c-ede534931545.png)

However when I open another application and leave the unity window, when I return (still in play mode, mind you), the textures have gone black. I am wondering if its something to do with unity unloading them from memory?
![screen shot 2018-07-17 at 23 29 22](https://user-images.githubusercontent.com/41355080/42859574-72cff5bc-8a19-11e8-8266-c6074add0f72.png)

Any input would be greatly appreciated! I've fiddled myself a bit, but am not so good with compute shaders especially. I have been working on modifying your implementation (which is excellent, by the way) into a more "user friendly" skybox system. Basically I added a button to generate the textures, and reworked the RenderSky shader to work with unity's skybox input slot. Everything works! Except this defocusing issue.

Any thoughts?

**Comment by Scrawk** [comment]
try calling 'm_model.BindToMaterial(m_material);' in OnRenderImage or OnApplicationFocus.

**Comment by antiquitymaster37** [comment]
Both seem to fix it. However, there is still about a frame or two of black before it goes back to normal. I am curious as to why this is.

I started selectively commenting out bits of the "bind to material" function and I think I narrowed it down to these three lines.

`Vector3 solarIrradiance = ToVector(Wavelengths, SolarIrradiance, lambdas, 1.0);
mat.SetVector("solar_irradiance", solarIrradiance);`

`Vector3 rayleighScattering = ToVector(Wavelengths, RayleighScattering, lambdas, LengthUnitInMeters);
mat.SetVector("rayleigh_scattering", rayleighScattering);`

`Vector3 mieScattering = ToVector(Wavelengths, MieScattering, lambdas, LengthUnitInMeters);
mat.SetVector("mie_scattering", mieScattering);`

In the "Render Sky" shader, the "solar_irradiance" is set and returned in "GetSolarRadiance" functions, but I don't see any float3 named "rayleigh_scattering" or "mie scattering" or where they would be used. Very odd! I will keep playing with it and see what I come up with

**Comment by danielshervheim** [comment]
That seems to fix it, however there is still about a frame or two of black textures.

I tried debugging by using `m_material.GetFloat("sun_angular_radius");` in the update method.

When I first go into play mode, it prints out what you would expect (~0.0046).
![screen shot 2018-07-18 at 10 56 21](https://user-images.githubusercontent.com/41355080/42893182-48a18f48-8a79-11e8-9cc8-7307543ec279.png)

However, when I leave unity and open up another application, then go back in, I get an 'material doesn't have float or range property' for a few frames, and the angular radius (and presumably all other variables set in code) have a value of 0, and then in the next frame its back to normal.
![screen shot 2018-07-18 at 10 56 32](https://user-images.githubusercontent.com/41355080/42893270-77c49c52-8a79-11e8-90c7-0b9c749f0931.png)

Very odd! I will keep looking into it. Ideally there would be no lag.

**Comment by danielshervheim** [comment]
Interesting, if I add `sun_angular_radius("sun_angular_radius", Float) = 0.00467499997466803` into the Properties block of `RenderSky.shader` then I don't get any error.

**Comment by danielshervheim** [comment]
So if I replace the Properties block in RenderSky.shader

![screen shot 2018-07-18 at 11 22 45](https://user-images.githubusercontent.com/41355080/42894639-f737c006-8a7c-11e8-9093-97f9ef952ea1.png)

With this (every variable changed in BindToMaterial) as a property

![screen shot 2018-07-18 at 11 22 59](https://user-images.githubusercontent.com/41355080/42894655-0245e2c0-8a7d-11e8-83e0-ed9beaf1dad8.png)

There is no errors, even WITHOUT calling BindToMaterial in every OnRenderImage or OnApplicationFocus.

Not sure why, just glad its fixed!!
